### ISSUE TITLE
the website no longer requires nav

### ISSUE THREAD

**Issue by xproot** [nickandfloppy/NetDrivers#22]
this has broken my setup which would swap nav for a new one automatically and since it doesn't require it it doesn't trigger my function pls fix or i call the cia

**Comment by floppydisk05** [comment]
![image](https://user-images.githubusercontent.com/32990087/173347877-8dc1b2c0-6bfc-4401-aed2-71c180c153f9.png)

**Comment by floppydisk05** [comment]
no

**Comment by floppydisk05** [comment]
"completed"
thanks github

**Comment by xproot** [comment]
thanks for fixing it

**Comment by floppydisk05** [comment]
I literally added wontfix

**Comment by xproot** [comment]
nwoat
asdfsag
