### ISSUE TITLE
SQL injection in batch.php

### ISSUE THREAD

**Issue by wireghoul** [nickandfloppy/NetDrivers#23]
The file `batch.php` is vulnerable to SQL injection.
User supplied input from `$_GET['files']` is converted to an array on lines 22 & 23:
```php
   $files    = '[' . $_GET['files'] . ']';
   $filesarr = json_decode($files, true, 512, JSON_THROW_ON_ERROR);
```
This array is then enumerated in a loop from line 27 -31 and is concatenated unsafely into the SQL query on line 29.
```php
   foreach ($filesarr as $file) {
      if ($i != 0) $sql = $sql . " OR ";
      $sql = $sql . "id = " . $file; //<-----HERE
      $i   = $i + 1;
   }
```
https://github.com/nickandfloppy/NetDrivers/blob/master/batch.php#29

**Comment by floppydisk05** [comment]
Removed the file, It'll probably be redone entirely in a less garbage way in the future
