### ISSUE TITLE
All the commits appear on my fork instead of the base repository

### ISSUE THREAD

**Issue by HIDEN64** [nickandfloppy/NetDrivers#6]
...I have no idea how this happened.
![image](https://user-images.githubusercontent.com/74623886/164188662-cc494b2e-5c60-4e0a-b679-786a03169800.png)
![image](https://user-images.githubusercontent.com/74623886/164188741-37d2f10d-b047-45e9-ab45-0acf682c9dbc.png)

**Comment by MrAureliusR** [comment]
That's... the whole point of forking something. You do work on your fork and then submit a pull request.

**Comment by floppydisk05** [comment]
What the fuck

**Comment by floppydisk05** [comment]
Thats super weird because I just did a test commit and it went straight to the correct repo

**Comment by nick99nack** [comment]
Wait a minute, there were previously commits on the correct repo and now they're gone

**Comment by floppydisk05** [comment]
No, I already did that

**Comment by floppydisk05** [comment]
apparently you can make a pr even if its not your fork for whatever reason

**Comment by floppydisk05** [comment]
the fucking what the commits are just gone now

**Comment by floppydisk05** [comment]
Re-added remote urls. now we pray and wait

**Comment by nick99nack** [comment]
wtf, it reverted again

**Comment by nick99nack** [comment]
So what happened is, at some point the git was moved from gitea to github for some reason. Gitea repo remains, but it was set up to push out changes to github every night. Basically, gitea kept pushing out the old copy of the repo every night at like 3AM or something.

**Comment by floppydisk05** [comment]
it's every 8 hours lol (I think anyway)

doesn't really explain why it was all going to hiden's thing though I think that was something I fixed in the config

**Comment by floppydisk05** [comment]
github no

**Comment by nick99nack** [comment]
Changes weren't going there, she just had a newer copy of the repo. That commit I did was also on the regular repo to begin with until Gitea wiped it out. The remote URL was correct.

**Comment by floppydisk05** [comment]
oh shit you're right
